---
- hosts: all
  become: yes

  vars_files:
    - vars/default_vars.yml
    # ansible-core 2.19 disallows (thankfully not needed!)
    #- vars/{{ ansible_local.local_facts.os_ver }}.yml
    - /etc/iiab/local_vars.yml
    - /etc/iiab/iiab_state.yml

  roles:
    - { role: 0-init }
    - { role: "{{ role_to_run }}" }
