# Administration and Monitoring/Assessment Tools

- name: ...IS BEGINNING ======================================
  meta: noop

- name: TRANSMISSION
  include_role:
    name: transmission
  when: transmission_install and not (os_ver == "ubuntu-2404" and not is_trisquel or os_ver == "ubuntu-2504")    # Also excludes os == "linuxmint-22", for #3756 (whereas Transmission works on Trisquel 12, Debian 13, Ubuntu 25.10!)

- name: AWSTATS
  include_role:
    name: awstats
  when: awstats_install

- name: MATOMO
  include_role:
    name: matomo
  when: matomo_install

- name: MONIT
  include_role:
    name: monit
  when: monit_install

- name: PHPMYADMIN
  include_role:
    name: phpmyadmin
  when: phpmyadmin_install

- name: VNSTAT
  include_role:
    name: vnstat
  when: vnstat_install

- name: Recording STAGE 8 HAS COMPLETED ======================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=8'
