- name: Assert that var hostapd_enabled is defined
  assert:
    that: hostapd_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'hostapd_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var dnsmasq_enabled is defined
  assert:
    that: dnsmasq_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'dnsmasq_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var bluetooth_enabled is defined
  assert:
    that: bluetooth_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'dnsmasq_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var sshd_enabled is defined
  assert:
    that: sshd_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'sshd_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var tailscale_enabled is defined
  assert:
    that: tailscale_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'tailscale_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var remoteit_enabled is defined
  assert:
    that: remoteit_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'remoteit_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var admin_console_enabled is defined
  assert:
    that: admin_console_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'admin_console_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var squid_enabled is defined
  assert:
    that: squid_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'squid_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var cups_enabled is defined
  assert:
    that: cups_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'cups_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var samba_enabled is defined
  assert:
    that: samba_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'samba_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var usb_lib_enabled is defined
  assert:
    that: usb_lib_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'usb_lib_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var azuracast_enabled is defined
  assert:
    that: azuracast_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'azuracast_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var gitea_enabled is defined
  assert:
    that: gitea_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'gitea_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var jupyterhub_enabled is defined
  assert:
    that: jupyterhub_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'jupyterhub_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var lokole_enabled is defined
  assert:
    that: lokole_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'lokole_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var mysql_enabled is defined
  assert:
    that: mysql_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'mysql_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var mediawiki_enabled is defined
  assert:
    that: mediawiki_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'mediawiki_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var mosquitto_enabled is defined
  assert:
    that: mosquitto_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'mosquitto_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var nodejs_enabled is defined
  assert:
    that: nodejs_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'nodejs_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var nodered_enabled is defined
  assert:
    that: nodered_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'nodered_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var nextcloud_enabled is defined
  assert:
    that: nextcloud_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'nextcloud_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var wordpress_enabled is defined
  assert:
    that: wordpress_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'wordpress_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var kalite_enabled is defined
  assert:
    that: kalite_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'kalite_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var kolibri_enabled is defined
  assert:
    that: kolibri_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'kolibri_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var kiwix_enabled is defined
  assert:
    that: kiwix_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'kiwix_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var postgresql_enabled is defined
  assert:
    that: postgresql_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'postgresql_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var moodle_enabled is defined
  assert:
    that: moodle_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'moodle_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var mongodb_enabled is defined
  assert:
    that: mongodb_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'mongodb_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var sugarizer_enabled is defined
  assert:
    that: sugarizer_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'sugarizer_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var osm_vector_maps_enabled is defined
  assert:
    that: osm_vector_maps_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'osm_vector_maps_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var transmission_enabled is defined
  assert:
    that: transmission_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'transmission_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var awstats_enabled is defined
  assert:
    that: awstats_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'awstats_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var matomo_enabled is defined
  assert:
    that: matomo_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'matomo_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var monit_enabled is defined
  assert:
    that: monit_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'monit_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var munin_enabled is defined
  assert:
    that: munin_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'munin_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var phpmyadmin_enabled is defined
  assert:
    that: phpmyadmin_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'phpmyadmin_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var vnstat_enabled is defined
  assert:
    that: vnstat_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'vnstat_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var yarn_enabled is defined
  assert:
    that: yarn_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'yarn_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var captiveportal_enabled is defined
  assert:
    that: captiveportal_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'captiveportal_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var internetarchive_enabled is defined
  assert:
    that: internetarchive_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'internetarchive_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var luanti_enabled is defined
  assert:
    that: luanti_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'luanti_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var calibreweb_enabled is defined
  assert:
    that: calibreweb_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'calibreweb_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var calibre_enabled is defined
  assert:
    that: calibre_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'calibre_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var pbx_enabled is defined
  assert:
    that: pbx_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'pbx_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that var network_enabled is defined
  assert:
    that: network_enabled is defined
    fail_msg: "VARIABLE MUST BE DEFINED: 'network_enabled' NEEDS A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes
